# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-11 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_area_areacliente_cliente_detallepedido_pedido_producto_productoareacliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacliente',
            name='id_cliente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='API.Cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='area',
            name='area',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='areacliente',
            name='id_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Area'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='id_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Pedido'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Producto'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='amaterno',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='apaterno',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Empleado'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='productoareacliente',
            name='id_area_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.AreaCliente'),
        ),
        migrations.AlterField(
            model_name='productoareacliente',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Producto'),
        ),
    ]
